---
all:
  children:
    deploy_dev:
      hosts:
        dev-01.deploy.local:
          ansible_host: 192.168.101.202
    deploy_prod:
      hosts:
        prod-01.deploy.local:
          ansible_host: 172.31.79.50
