---
# App deployment related tasks.

- name: Ensure npm packages are installed.
  block:
    - name: Check for existence of node_modules directory.
      stat:
        path: "../site/docroot/node_modules"
      register: node_modules
      delegate_to: localhost
      changed_when: false

    - name: Install npm packages.
      command: "npm install"
      args:
        chdir: "../site/docroot"
      delegate_to: localhost
      when: not node_modules.stat.exists

- name: Run Gulp build.
  command: "npx gulp build"
  args:
    chdir: "../site/docroot"
  delegate_to: localhost

- name: Rsync site files into place.
  synchronize:
    src: "{{ playbook_dir | dirname }}/site/"
    dest: "{{ app_vhost_dir }}/"
    private_key: "{{ ansible_ssh_private_key_file }}"
  when: "'prod' in app_hostname"

- name: Template index.html file into place.
  template:
    src: "index.html.j2"
    dest: "{{ app_vhost_dir }}/{{ app_docroot_dir }}/index.html"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Perform a minimal deployment test.
  block:
    - name: Download the index page from the local machine.
      get_url:
        url: "http://{{ app_hostname }}"
        dest: "/tmp/index.{{ ansible_date_time.iso8601 }}.html"
        url_username: "{{ app_htpasswd_name | default(omit) }}"
        url_password: "{{ app_htpasswd_password | default(omit) }}"
      register: response
      changed_when: false
      delegate_to: localhost

    - assert:
        that:
          - "response.status_code == 200"
        msg: "The homepage could not be reached."

    - assert:
        that:
          - "ansible_date_time.iso8601 in lookup('file', response.dest)"
        msg: "The homepage does not contain a timestamp matching Ansible's."
