---
# App deployment related tasks.

- name: Run Gulp build.
  command: "gulp build"
  args:
    chdir: "../site/docroot"
  delegate_to: localhost

- name: Rsync site files into place.
  synchronize:
    src: "../site/"
    dest: "{{ app_vhost_dir }}/"
    private_key: "{{ ansible_ssh_private_key_file }}"

- name: Template index.html file into place.
  template:
    src: "index.html.j2"
    dest: "{{ app_vhost_dir }}/{{ app_docroot_dir }}/index.html"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"

- name: Ensure file ownership and permissions are correct.
  command: "{{ item }}"
  args:
    chdir: "{{ app_vhost_dir }}"
    warn: false
  with_items:
    - "chown -R {{ app_user }}:{{ app_user }} ."
    - "find . -type d -exec chmod 755 {} \\;"
    - "find . -type f -exec chmod 644 {} \\;"
  changed_when: false
  become: true

- name: Perform a minimal deployment test.
  block:
    - name: Download the index page from the local machine.
      get_url:
        url: "http://{{ app_hostname }}"
        dest: "/tmp/index.{{ ansible_date_time.iso8601 }}.html"
        url_username: "{{ app_htpasswd_name | default(omit) }}"
        url_password: "{{ app_htpasswd_password | default(omit) }}"
      register: response
      changed_when: false
      delegate_to: localhost

    - assert:
        that:
          - "response.status_code == 200"
        msg: "The homepage could not be reached."

    - assert:
        that:
          - "ansible_date_time.iso8601 in lookup('file', response.dest)"
        msg: "The homepage does not contain a timestamp matching Ansible's."
